server.port=8080
server.servlet.context-path=/api/diamond

spring.datasource.url=jdbc:postgresql://diamond-postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

logging.level.org.springframework=INFO
logging.level.com.zbs=INFO

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

spring.main.allow-bean-definition-overriding=true
spring.application.name=de

spring.web.resources.static-locations=file:/app/uploads/
spring.mvc.static-path-pattern=/uploads/**

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000
app.jwt.verification-expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-email-verification-url=${FRONTEND_EMAIL_VERIFICATION_URL}

report.images.folder=/app/uploads/reports

spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.resolve-lazily=true