-- The suppliers the customer is bringing themselves.
--
-- WHAT THIS IS FOR
--
-- A customer often arranges part of their own day: their own photographer, a
-- particular mehndi artist, a cake maker the family has used for twenty years.
-- The venue has to know who those people are — they need access, a delivery
-- window, a parking space and a contact on the day — and the terms the
-- customer agrees to on the last step say the venue may cancel the booking
-- over an undeclared third party. So the declaration matters on both sides.
--
-- Until now the journey offered one free-text box, `txt_external_supplier_
-- remarks`, into which a customer might write anything from "none" to three
-- paragraphs containing two names and a phone number. Nobody can plan from
-- that, nobody can filter it, and nobody can ring anybody on the morning of
-- the event without reading prose first.
--
-- WHY A TABLE RATHER THAN JSON
--
-- Because the office reads this. A supplier is a row somebody looks up, sorts
-- by, and telephones — the operations most obviously served by columns. A JSON
-- blob would have been quicker to write here and would have moved the cost to
-- every query the admin portal ever runs against it.
--
-- The free-text column stays. It is the right place for the things that are
-- genuinely a sentence — "the florist will arrive with the cake" — and there
-- are live bookings whose supplier details exist only there.

CREATE TABLE IF NOT EXISTS event_external_supplier (
    ser_event_external_supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ser_event_master_id            INTEGER NOT NULL
        REFERENCES event_master (ser_event_master_id),

    -- What they do: "Photographer", "Mehndi artist", "Cake". Free text rather
    -- than a lookup, because the whole point of this table is the supplier the
    -- venue has not thought of, and a dropdown of known kinds would send those
    -- straight back into the notes box this exists to empty.
    txt_supplier_type              VARCHAR(120),
    txt_supplier_name              VARCHAR(255),

    txt_contact_name               VARCHAR(255),
    txt_contact_phone              VARCHAR(60),
    txt_contact_email              VARCHAR(255),

    -- Arrival window, access needs, anything that is genuinely a sentence.
    txt_notes                      TEXT,

    num_display_order              INTEGER,

    -- BaseEntity's audit columns, spelled the way the rest of the schema
    -- spells them so the same mapped superclass covers this table too.
    bln_is_active                  BOOLEAN DEFAULT TRUE,
    bln_is_approved                BOOLEAN,
    bln_is_deleted                 BOOLEAN DEFAULT FALSE,
    created_by                     INTEGER,
    created_date                   TIMESTAMP(6),
    updated_by                     INTEGER,
    updated_date                   TIMESTAMP(6)
);

-- Every read of this table is "the suppliers for this booking".
CREATE INDEX IF NOT EXISTS idx_event_external_supplier_event
    ON event_external_supplier (ser_event_master_id);
