-- What kind of supplier the customer is bringing, from a list the office keeps.
--
-- WHY A LOOKUP AND NOT THE FREE TEXT IT REPLACES
--
-- V18 made `txt_supplier_type` free text, and gave a reason: the whole point of
-- declaring a supplier is the one the venue has not thought of, and a dropdown
-- of known kinds would send those straight back into the notes box the step
-- exists to empty.
--
-- That reason was about *coverage*, and it is answered better by letting the
-- office add a category than by asking every customer to invent a word. Free
-- text gives you "DJ", "dj", "Disc Jockey", "Music", "dj + sound" as five
-- different things, so nothing can be counted, filtered, or driven from the
-- category — which is what the office actually wants to do with it: see every
-- photographer arriving next Saturday, or give the mehndi artist different
-- access instructions from the cake maker.
--
-- The escape hatch stays. Every supplier still has a free-text note, and the
-- office can add a category in seconds when a new trade turns up.
--
-- WHY THE OLD COLUMN GOES
--
-- Two ways to say the same thing is the modelling error being removed here, not
-- one to introduce. So the type is migrated into a category and the column is
-- dropped — losslessly: anything that does not match a seeded category becomes
-- a category of its own rather than being discarded.

CREATE TABLE IF NOT EXISTS external_supplier_category (
    ser_supplier_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Unique, case-insensitively, so the list cannot grow a "DJ" beside a "dj".
    txt_name                 VARCHAR(120) NOT NULL,

    -- Shown under the name on the journey, to settle "does my cousin doing the
    -- flowers count as a florist?" without a telephone call.
    txt_description          TEXT,

    num_display_order        INTEGER,

    bln_is_active            BOOLEAN DEFAULT TRUE,
    bln_is_approved          BOOLEAN,
    bln_is_deleted           BOOLEAN DEFAULT FALSE,
    created_by               INTEGER,
    created_date             TIMESTAMP(6),
    updated_by               INTEGER,
    updated_date             TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_external_supplier_category_name
    ON external_supplier_category (LOWER(txt_name))
    WHERE bln_is_deleted = false;

-- The trades a UK events venue is actually asked about. Not exhaustive on
-- purpose — the office adds to it, and the list being short is what keeps the
-- journey's dropdown scannable rather than a wall of options nobody reads.
INSERT INTO external_supplier_category (txt_name, txt_description, num_display_order,
                                        bln_is_active, bln_is_deleted, created_date)
SELECT name, description, ord, true, false, now()
FROM (VALUES
    ('Photographer',    'Stills photography on the day.',                                  10),
    ('Videographer',    'Film and video, including drone operators.',                      20),
    ('DJ',              'Music and sound. Tell us if they need power or a sound check.',   30),
    ('Live musicians',  'Bands, singers, dhol players, string quartets.',                  40),
    ('Mehndi artist',   'Henna, usually needing a table and good light.',                  50),
    ('Hair and make-up','Working on site before the event starts.',                         60),
    ('Cake',            'The cake maker, and whoever is delivering it.',                   70),
    ('Florist',         'Flowers you are arranging yourself.',                             80),
    ('Entertainment',   'Magicians, dancers, childrens entertainers, anything performed.',  90),
    ('Transport',       'Cars, buses and anything arriving that needs parking.',           100),
    ('Officiant',       'Imam, registrar, celebrant.',                                     110),
    ('Other',           'Anything that does not fit above. Tell us in the notes.',         900)
) AS seed(name, description, ord)
WHERE NOT EXISTS (
    SELECT 1 FROM external_supplier_category c
    WHERE LOWER(c.txt_name) = LOWER(seed.name) AND c.bln_is_deleted = false
);

ALTER TABLE event_external_supplier
    ADD COLUMN IF NOT EXISTS ser_supplier_category_id BIGINT
        REFERENCES external_supplier_category (ser_supplier_category_id);

-- Anything already declared under a name nobody seeded becomes a category, so
-- the migration loses nothing. `bln_is_active = false`: it is a real category
-- because somebody used it, and the office decides whether to offer it going
-- forward rather than inheriting whatever a customer once typed.
INSERT INTO external_supplier_category (txt_name, txt_description, num_display_order,
                                        bln_is_active, bln_is_deleted, created_date)
SELECT DISTINCT ON (LOWER(TRIM(s.txt_supplier_type)))
       TRIM(s.txt_supplier_type),
       'Carried over from a supplier declared before categories existed.',
       800,
       false, false, now()
FROM event_external_supplier s
WHERE COALESCE(TRIM(s.txt_supplier_type), '') <> ''
  AND NOT EXISTS (
      SELECT 1 FROM external_supplier_category c
      WHERE LOWER(c.txt_name) = LOWER(TRIM(s.txt_supplier_type)) AND c.bln_is_deleted = false
  );

UPDATE event_external_supplier s
SET ser_supplier_category_id = c.ser_supplier_category_id
FROM external_supplier_category c
WHERE s.ser_supplier_category_id IS NULL
  AND COALESCE(TRIM(s.txt_supplier_type), '') <> ''
  AND LOWER(c.txt_name) = LOWER(TRIM(s.txt_supplier_type))
  AND c.bln_is_deleted = false;

ALTER TABLE event_external_supplier DROP COLUMN IF EXISTS txt_supplier_type;

CREATE INDEX IF NOT EXISTS idx_event_external_supplier_category
    ON event_external_supplier (ser_supplier_category_id);

COMMENT ON TABLE external_supplier_category IS
    'The kinds of supplier a customer may declare. Maintained by the office; the journey offers the active ones.';
