-- The moments a running order has, per event type.
--
-- WHAT THIS REPLACES
--
-- A hardcoded map in the control panel's booking form:
--
--   const RUNNING_ORDER_FIELD_MAPPING = {
--     2: [ ...sixteen wedding moments... ],
--     3: [ 'txtGuestArrival', 'txtBrideEntrance', 'txtGroomEntrance', ... ],
--     4: [ ... ], 5: [ ... ],
--   };
--
-- keyed by event_type.ser_event_type_id — a column the business assigns by
-- adding rows on the Event Types screen. A map from a business-editable
-- surrogate key to behaviour is guaranteed to drift, and it has: in this
-- database id 2 is "Corporate Event", so the sixteen *wedding* moments are
-- filed under the corporate event, while id 3 ("Wedding") gets a six-moment
-- list with no Nikah and no Barat arrival. Ids 4 and 5 are Mehndi and Awards
-- Dinner, both offered a "Bride entrance".
--
-- It has never shown: the code read RUNNING_ORDER_FIELD_MAPPING[2] with the
-- line that uses the event type commented out directly above it, so every
-- booking gets the sixteen whatever it is for. Every live booking is event
-- type 7 (Walima), which is in none of the keys — so the map has never once
-- selected anything, and uncommenting that line would have started handing
-- wedding bookings a list with the Nikah missing.
--
-- WHY EVERY TYPE IS SEEDED WITH ALL SIXTEEN
--
-- Because narrowing is what loses data. The form submits only the fields it
-- has rendered, so the first save of a booking whose list has shrunk clears
-- whatever was stored in the moments that stopped being shown. Seeding every
-- type with the full list reproduces exactly what is on screen today, for
-- every booking, so this migration changes nothing anybody can see.
--
-- Narrowing then becomes the business's own decision, made per type with the
-- bookings in front of them, rather than a code change that silently drops
-- stored times.

CREATE TABLE IF NOT EXISTS event_type_running_order_moment (
    ser_moment_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ser_event_type_id   integer NOT NULL REFERENCES event_type (ser_event_type_id),
    -- The column on event_running_order this moment fills, e.g. 'txtNikah'.
    txt_field           character varying(64) NOT NULL,
    num_display_order   integer NOT NULL,
    bln_is_active       boolean NOT NULL DEFAULT true,
    bln_is_deleted      boolean NOT NULL DEFAULT false,
    bln_is_approved     boolean DEFAULT true,
    created_by          integer,
    created_date        timestamp(6) without time zone DEFAULT now(),
    updated_by          integer,
    updated_date        timestamp(6) without time zone,
    CONSTRAINT event_type_running_order_moment_unique UNIQUE (ser_event_type_id, txt_field)
);

CREATE INDEX IF NOT EXISTS idx_running_order_moment_type
    ON event_type_running_order_moment (ser_event_type_id, num_display_order);

-- In the order the day runs, which is the order they are read down.
INSERT INTO event_type_running_order_moment (ser_event_type_id, txt_field, num_display_order)
SELECT t.ser_event_type_id, m.txt_field, m.num_display_order
FROM event_type t
CROSS JOIN (VALUES
    ('txtGuestArrival',      10),
    ('txtBrideGuestArrival', 20),
    ('txtGroomGuestArrival', 30),
    ('txtBaratArrival',      40),
    ('txtNikah',             50),
    ('txtBrideEntrance',     60),
    ('txtGroomEntrance',     70),
    ('txtCouplesEntrance',   80),
    ('txtDua',               90),
    ('txtRingExchange',     100),
    ('txtCakeCutting',      110),
    ('txtRams',             120),
    ('txtSpeeches',         130),
    ('txtDance',            140),
    ('txtMeal',             150),
    ('txtEndOfNight',       160)
) AS m (txt_field, num_display_order)
WHERE COALESCE(t.bln_is_deleted, false) = false
ON CONFLICT (ser_event_type_id, txt_field) DO NOTHING;
