-- ═══════════════════════════════════════════════════════════════════════
-- The event reference has to be unique.
--
-- txt_event_master_code is DE-<yy>-<serial>, and it is the number a customer
-- quotes on the phone and the number staff search on. It was generated by
-- reading the highest code for the year and adding one, with nothing in the
-- database preventing two of them: two customers starting a booking within the
-- same moment both read DE-26-1004 and both were given DE-26-1005.
--
-- Nothing then complains. There are simply two events with the same reference,
-- and the next person to search for it gets two answers.
-- ═══════════════════════════════════════════════════════════════════════

DO $$
DECLARE
    duplicates text;
BEGIN
    -- The table may not exist yet on a database being built from scratch by
    -- Hibernate, in which case there is nothing to constrain here — the entity
    -- mapping carries the constraint for that path.
    IF to_regclass('public.event_master') IS NULL THEN
        RAISE NOTICE 'event_master does not exist yet; skipping.';
        RETURN;
    END IF;

    -- Refuse to add the constraint over data that already violates it, and say
    -- exactly which references are affected.
    --
    -- Failing the migration is deliberate. Silently skipping would leave the
    -- duplicates in place and the constraint absent, which is the state this
    -- migration exists to end; and de-duplicating automatically would mean
    -- renumbering an event whose reference a customer may already have been
    -- given. Someone has to decide which one keeps the number.
    SELECT string_agg(txt_event_master_code || ' (x' || n || ')', ', ' ORDER BY txt_event_master_code)
      INTO duplicates
      FROM (
        SELECT txt_event_master_code, count(*) AS n
          FROM event_master
         WHERE txt_event_master_code IS NOT NULL
         GROUP BY txt_event_master_code
        HAVING count(*) > 1
      ) d;

    IF duplicates IS NOT NULL THEN
        RAISE EXCEPTION
            'Cannot make event references unique: these are already duplicated — %. '
            'Decide which event keeps each reference, renumber the others, then '
            'run the migration again.', duplicates;
    END IF;

    -- A partial index: rows created before codes were assigned have NULL, and
    -- those are not duplicates of each other.
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
         WHERE schemaname = 'public' AND indexname = 'ux_event_master_code'
    ) THEN
        CREATE UNIQUE INDEX ux_event_master_code
            ON event_master (txt_event_master_code)
         WHERE txt_event_master_code IS NOT NULL;
    END IF;
END $$;
